### ISSUE TITLE
workshop: initialize the map

### ISSUE THREAD

**Issue by danduk82** [danduk82/foss4g2021#5]

**Comment by danduk82** [comment]
@bchapuis I am currently getting this kind of errors when accessing maputinik for the first time. Are there some changes to be made in the osm vecto tileset?

```
<S_QUOTED_IDENTIFIER>

        at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:26917) ~[jsqlparser-4.1.jar:?]
        at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:26753) ~[jsqlparser-4.1.jar:?]
        at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:93) ~[jsqlparser-4.1.jar:?]
        at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:188) ~[jsqlparser-4.1.jar:?]
        at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:63) ~[jsqlparser-4.1.jar:?]
        at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:38) ~[jsqlparser-4.1.jar:?]
        at com.baremaps.tile.postgres.PostgresQuery.parse(PostgresQuery.java:65) ~[baremaps-tile-postgres-0.6.0.jar:?]
        ... 76 more
[ERROR] 2021-09-22 17:35:33.077 [servicetalk-global-executor-1-6] EditorResources - Tile error
java.lang.IllegalArgumentException: The query is malformed.
        Query:
                SELECT id, tags, geom
FROM osm_ways_z${zoom}
WHERE tags ? 'aerialway'

        at com.baremaps.tile.postgres.PostgresQuery.parse(PostgresQuery.java:69) ~[baremaps-tile-postgres-0.6.0.jar:?]
        at com.baremaps.tile.postgres.PostgresQuery.<init>(PostgresQuery.java:38) ~[baremaps-tile-postgres-0.6.0.jar:?]
        at com.baremaps.server.ogcapi.Conversions.lambda$asPostgresQuery$0(Conversions.java:35) ~[baremaps-server-ogcapi-0.6.0.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at com.baremaps.server.ogcapi.Conversions.asPostgresQuery(Conversions.java:36) ~[baremaps-server-ogcapi-0.6.0.jar:?]
        at com.baremaps.server.editor.EditorResources.getTile(EditorResources.java:174) ~[baremaps-server-editor-0.6.0.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-2.32.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[jersey-server-2.32.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[jersey-server-2.32.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[jersey-server-2.32.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[jersey-server-2.32.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[jersey-server-2.32.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[jersey-server-2.32.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[jersey-server-2.32.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) ~[jersey-server-2.32.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-2.32.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-2.32.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.32.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.32.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-2.32.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[jersey-common-2.32.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) ~[jersey-server-2.32.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) ~[jersey-server-2.32.jar:?]
        at io.servicetalk.http.router.jersey.DefaultJerseyStreamingHttpRouter.handle0(DefaultJerseyStreamingHttpRouter.java:259) ~[servicetalk-http-router-jersey-0.40.1.jar:0.40.1]
        at io.servicetalk.http.router.jersey.DefaultJerseyStreamingHttpRouter.access$100(DefaultJerseyStreamingHttpRouter.java:78) ~[servicetalk-http-router-jersey-0.40.1.jar:0.40.1]
        at io.servicetalk.http.router.jersey.DefaultJerseyStreamingHttpRouter$3.handleSubscribe(DefaultJerseyStreamingHttpRouter.java:191) ~[servicetalk-http-router-jersey-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.Single.handleSubscribe(Single.java:2582) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.Single.delegateSubscribe(Single.java:2538) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.SingleFlatMapCompletable.handleSubscribe(SingleFlatMapCompletable.java:45) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.Completable.lambda$subscribeWithContext$3(Completable.java:2203) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.ContextPreservingConsumer.accept(ContextPreservingConsumer.java:40) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.NoopOffloader.offloadSubscribe(NoopOffloader.java:80) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.Completable.subscribeWithContext(Completable.java:2202) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.Completable.subscribeInternal(Completable.java:1695) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.SourceToFuture$CompletableToFuture.createAndSubscribe(SourceToFuture.java:162) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.Completable.toFuture(Completable.java:1680) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.http.api.StreamingHttpServiceToBlockingStreamingHttpService.handle(StreamingHttpServiceToBlockingStreamingHttpService.java:57) ~[servicetalk-http-api-0.40.1.jar:0.40.1]
        at io.servicetalk.http.api.BlockingStreamingToStreamingService$1.handleSubscribe(BlockingStreamingToStreamingService.java:129) ~[servicetalk-http-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.Single.handleSubscribe(Single.java:2582) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.Single.delegateSubscribe(Single.java:2538) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.OnErrorResumeSingle.handleSubscribe(OnErrorResumeSingle.java:44) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.Single.delegateSubscribe(Single.java:2538) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.SingleFlatMapPublisher.handleSubscribe(SingleFlatMapPublisher.java:44) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.PublisherSubscribeShareContext.handleSubscribe(PublisherSubscribeShareContext.java:34) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.Publisher.lambda$subscribeWithContext$16(Publisher.java:3659) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.ContextPreservingConsumer.accept(ContextPreservingConsumer.java:40) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.NoopOffloader.offloadSubscribe(NoopOffloader.java:68) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.Publisher.subscribeWithContext(Publisher.java:3658) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.Publisher.subscribeInternal(Publisher.java:3345) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.SingleFlatMapPublisher$SubscriberImpl.onSuccess(SingleFlatMapPublisher.java:95) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.OnErrorResumeSingle$ResumeSubscriber.onSuccess(OnErrorResumeSingle.java:78) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.ContextPreservingSingleSubscriber.onSuccess(ContextPreservingSingleSubscriber.java:75) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.AbstractSubmitSingle.lambda$handleSubscribe$0(AbstractSubmitSingle.java:49) ~[servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at io.servicetalk.concurrent.api.ContextPreservingRunnable.run(ContextPreservingRunnable.java:43) [servicetalk-concurrent-api-0.40.1.jar:0.40.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "{" "{"
    at line 2, column 17.
```

**Comment by bchapuis** [comment]
Yes, there were a couple of breaking changes, hence the 0.6.0 version.

An important one is the use of minzoom and maxzoom instead of minZoom and maxZoom to be conform with the TileJSON specification.

Another one is related to the injection of variables in the queries (your case). `osm_ways_z${zoom}` becomes osm_ways_z$zoom because the `{` and `}` are forbidden in table names. The JSQLParser only supports valid SQL queries.
